#!/usr/bin/env node
// Generates portal/prototypes.generated.json by scanning products/*/product.json
// and products/*/prototypes/*/prototype.json.
//
// This file is the single source of truth the Portal UI reads at runtime — see
// portal/app.js. It is machine-generated; do not hand-edit it (edit the
// product.json / prototype.json files instead and re-run `npm run generate`).
//
// This script assumes the tree is valid. Run `npm run validate` first (the
// `build` script does this for you). Any entry it cannot parse is skipped
// with a warning rather than crashing the whole build.

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { scanRepo } from './lib/scan.mjs';
import { getUpdatedAt } from './lib/git-time.mjs';
import { resolveThumbnail } from './lib/thumbnail.mjs';
import {
  ALLOWED_STATUSES,
  DEFAULT_PROTOTYPE_ENTRY,
  DEFAULT_PROTOTYPE_ORDER,
  DEFAULT_PROTOTYPE_VISIBLE,
} from './lib/constants.mjs';

const rootDir = process.cwd();
const OUTPUT_PATH = path.join(rootDir, 'portal', 'prototypes.generated.json');

function emptyStatusCounts() {
  return { draft: 0, review: 0, approved: 0, archived: 0 };
}

function toPosixPath(p) {
  return p.split(path.sep).join('/');
}

function main() {
  const { products: rawProducts } = scanRepo(rootDir);
  const products = [];
  const prototypes = [];

  for (const product of rawProducts) {
    if (product.error || !product.data) {
      console.warn(`[generate-portal] skipping product "${product.dirName}": ${product.error ?? 'invalid product.json'}`);
      continue;
    }
    const pData = product.data;
    const productId = pData.id ?? product.dirName;
    const productVisible = pData.visible !== false;

    const statusCounts = emptyStatusCounts();
    let latestUpdatedAt = null;
    let prototypeCount = 0;

    for (const prototype of product.prototypes) {
      if (prototype.error || !prototype.data) {
        console.warn(`[generate-portal] skipping prototype "${product.dirName}/${prototype.dirName}": ${prototype.error ?? 'invalid prototype.json'}`);
        continue;
      }
      const data = prototype.data;
      const prototypeVisible = data.visible !== false;
      if (!ALLOWED_STATUSES.includes(data.status)) {
        console.warn(`[generate-portal] skipping prototype "${product.dirName}/${prototype.dirName}": invalid status "${data.status}"`);
        continue;
      }

      const relativeDir = toPosixPath(path.relative(rootDir, prototype.dir));
      const url = `${relativeDir}/`;
      const updatedAt = getUpdatedAt(prototype.dir);
      const thumbnail = resolveThumbnail(prototype.dir, data.thumbnail);

      const entry = {
        id: data.id ?? prototype.dirName,
        name: data.name,
        description: data.description,
        status: data.status,
        owner: data.owner ?? '',
        tags: Array.isArray(data.tags) ? data.tags : [],
        entry: data.entry ?? DEFAULT_PROTOTYPE_ENTRY,
        thumbnail: thumbnail ? toPosixPath(path.join(relativeDir, thumbnail)) : null,
        visible: prototypeVisible,
        order: typeof data.order === 'number' ? data.order : DEFAULT_PROTOTYPE_ORDER,
        productId,
        productName: pData.name ?? product.dirName,
        url,
        sourcePath: relativeDir,
        updatedAt,
      };

      // Invisible prototypes are omitted entirely from the generated manifest
      // (section XXII: "应完全不出现在 Portal 中") but the files stay reachable
      // by direct URL since nothing on disk is removed.
      if (productVisible && prototypeVisible) {
        prototypes.push(entry);
        prototypeCount += 1;
        statusCounts[data.status] += 1;
        if (!latestUpdatedAt || updatedAt > latestUpdatedAt) latestUpdatedAt = updatedAt;
      }
    }

    if (!productVisible) continue;

    products.push({
      id: productId,
      name: pData.name,
      description: pData.description,
      order: typeof pData.order === 'number' ? pData.order : 100,
      visible: productVisible,
      prototypeCount,
      statusCounts,
      latestUpdatedAt,
    });
  }

  products.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));
  prototypes.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

  const manifest = {
    _comment: 'AUTO-GENERATED by scripts/generate-portal.mjs — do not edit by hand.',
    generatedAt: new Date().toISOString(),
    products,
    prototypes,
  };

  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  console.log(`[generate-portal] wrote ${products.length} product(s) and ${prototypes.length} prototype(s) to ${toPosixPath(path.relative(rootDir, OUTPUT_PATH))}`);
}

main();
